
name: main

on: push

env:
  KEY: "dummy"
  USER: dummy_user
  PASSWORD: dummy_pass

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo ${USER}
      - run: echo ${PASSWORD}
        if: contains(github.ref, 'master')

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    steps:
      - run: echo ${SSH_KEY}
